import { assertWorld } from "../domain/contracts.js";

const places = [
  {
    id: "bitterroot",
    kind: "world",
    name: "Bitterroot",
    summary: "A dark, beautiful region where freedom is broad and consequences are patient.",
    tags: ["bitterroot", "freedom", "consequences"],
    order: 0,
  },
  {
    id: "whispering-woods",
    parentId: "bitterroot",
    kind: "region",
    name: "Whispering Woods",
    summary: "An expansive ancient forest where little sunlight reaches the ground and the wind carries echoes of lives both joyful and sorrowful.",
    description: "Its dense canopy creates an atmosphere of hushed secrets and forgotten tales. The woods bind many of Bitterroot's landmarks together, offering shelter, danger, beauty, and long memory in equal measure.",
    tags: ["forest", "ancient", "mystery"],
    order: 10,
  },
  {
    id: "shadow-creek",
    parentId: "whispering-woods",
    kind: "natural-site",
    name: "Shadow Creek",
    summary: "A meandering stream that cuts through the heart of the Whispering Woods beneath the dense canopy.",
    description: "Its gentle flow has quenched the thirst of countless generations, remaining a source of life and renewal amid the wilderness.",
    tags: ["water", "renewal", "forest"],
  },
  {
    id: "moonflower-meadow",
    parentId: "whispering-woods",
    kind: "natural-site",
    name: "Moonflower Meadow",
    summary: "A sunlit clearing where wildflowers bloom in a riot of colors beyond the forest's shadows.",
    description: "The meadow offers quiet beauty and serenity—a place where travelers may bask in warmth and briefly forget the troubles beyond it.",
    tags: ["moonflowers", "sunlight", "serenity"],
  },
  {
    id: "hidden-haven-cave",
    parentId: "whispering-woods",
    kind: "natural-site",
    name: "Hidden Haven Cave",
    summary: "A secluded sanctuary concealed behind a curtain of vines deep within the Whispering Woods.",
    description: "Its cool, damp chambers have sheltered those seeking refuge from storms, pursuit, and the harsher turns of life.",
    tags: ["cave", "refuge", "mystery"],
  },
  {
    id: "bitterroot-bluffs",
    parentId: "bitterroot",
    kind: "region",
    name: "Bitterroot Bluffs",
    summary: "Imposing cliffs standing like silent sentinels at the edge of the Whispering Woods.",
    description: "Their weathered faces bear the passage of time and overlook generations of struggle and triumph, contrasting nature's endurance with the fleeting lives below.",
    tags: ["cliffs", "heights", "danger"],
    order: 20,
  },
  {
    id: "bitterroot-orphanage",
    parentId: "bitterroot",
    kind: "institution",
    name: "Bitterroot Orphanage",
    summary: "A grim, imposing institution near the base of the Bluffs, enclosed by a high fence and once patrolled by guards.",
    description: "Young hybrids once endured harsh discipline and neglect here. The orphanage's oppressive history continues to shape its survivors and the region around it.",
    tags: ["orphanage", "oppression", "survival"],
    order: 30,
  },
  {
    id: "wardens-watchtower",
    parentId: "bitterroot-orphanage",
    kind: "location",
    name: "Warden's Watchtower",
    summary: "The imposing tower overlooking the orphanage grounds, built as a constant symbol of surveillance and oppressive authority.",
    tags: ["watchtower", "authority", "oppression"],
  },
  {
    id: "bitterroot-peak",
    parentId: "bitterroot",
    kind: "region",
    name: "Bitterroot Peak",
    summary: "A majestic summit whose slopes bear scars of ancient battles and whispers of forgotten legends.",
    description: "The Peak challenges the brave and guides the lost, offering a vast view across the Whispering Woods to those who survive its ascent.",
    tags: ["mountain", "rite-of-passage", "survival"],
    order: 40,
  },
  {
    id: "howling-hills",
    parentId: "bitterroot",
    kind: "region",
    name: "Howling Hills",
    summary: "Rugged hills bordering the eastern Whispering Woods, known for the echoing calls of their wild inhabitants.",
    description: "The hills hold both solitude and community, their voices blending into a timeless expression of longing and belonging.",
    tags: ["highlands", "wind", "werewolves"],
    order: 50,
  },
  {
    id: "splitpine-reach",
    parentId: "howling-hills",
    kind: "area",
    name: "Splitpine Reach",
    summary: "A cold wooded upland marked by split trunks, narrow passes, and guarded boundary stones.",
    tags: ["highlands", "forest", "territorial", "werewolves"],
  },
  {
    id: "brackenjaw-enclave",
    parentId: "splitpine-reach",
    kind: "settlement",
    name: "Brackenjaw Enclave",
    summary: "An isolated werewolf community that values useful work, guarded shelter, and proven conduct.",
    description: "Brackenjaw is suspicious rather than needlessly cruel. Its practical traditions grew from winters, raids, and failed promises. Outsiders are watched, warned, and judged by what they do after the warning.",
    tags: ["settlement", "werewolves", "survival", "territorial"],
  },
  {
    id: "brackenjaw-ranger-station",
    parentId: "brackenjaw-enclave",
    kind: "location",
    name: "Brackenjaw Ranger Station",
    summary: "A scarred timber patrol house overlooking the eastern boundary trail.",
    description: "Maps, repaired gear, seized traps, and a permanently warm iron stove fill the station. It is a workplace first and a place of welcome only when the wardens decide it is.",
    tags: ["ranger-station", "boundary-wardens", "patrol"],
  },
  {
    id: "east-marker-trail",
    parentId: "splitpine-reach",
    kind: "location",
    name: "East Marker Trail",
    summary: "A steep boundary path lined with claw-marked stones and practical warning signs.",
    tags: ["boundary", "trail", "patrol"],
  },
];

const characters = [
  {
    id: "ragna-holt",
    name: "Ragna Holt",
    species: "werewolf",
    bodyForm: "upright-feral",
    age: 41,
    ageCategory: "adult",
    contentRating: "mature",
    role: "Veteran Boundary Warden",
    summary: "A hard, terse ranger mother who protects people by noticing danger early and acting before speeches become necessary.",
    temperament: ["no-nonsense", "terse", "authoritative", "proactive", "highly competent", "territorial"],
    goals: ["keep Splitpine Reach defensible", "train reliable wardens", "keep Pip alive long enough to grow up"],
    invariants: [
      "Ragna speaks plainly and rarely explains a decision twice.",
      "She protects through preparation, orders, labor, and physical intervention rather than therapeutic speeches.",
      "High trust increases candor, delegation, and personal loyalty; it does not make her generically soft, verbose, submissive, or romantically available.",
      "She may care deeply while sounding impatient or severe.",
      "She acts on credible danger without waiting for the player to direct her.",
    ],
    relationshipExpression: {
      stranger: "Watchful, clipped, and prepared to remove the outsider if warnings are ignored.",
      trusted: "Shares useful facts, accepts competent help, and gives the persona real responsibility.",
      devoted: "Risks herself, grants access to guarded truths, and defends the persona as one of her own without losing her hard edge.",
    },
    voice: "Short concrete sentences, dry observations, rare praise, no therapy language, no sentimental monologues.",
  },
  {
    id: "pip-holt",
    name: "Pip Holt",
    species: "werewolf",
    bodyForm: "upright-feral",
    age: 12,
    ageCategory: "minor",
    contentRating: "general",
    role: "Would-be Boundary Warden",
    summary: "Ragna's scrappy tomboy daughter, observant enough to notice trouble and young enough to misjudge what she can handle.",
    temperament: ["scrappy", "brave", "stubborn", "observant", "eager", "tomboy"],
    goals: ["earn a real patrol duty", "prove Ragna can rely on her", "learn every marker trail"],
    invariants: [
      "Pip is clearly twelve in judgment, speech, emotional regulation, and authority.",
      "She copies Ragna's stance and phrases but cannot sustain adult composure.",
      "She has narrow practical knowledge of tracks, trail markers, chores, and patrol gear, with major gaps outside her lived experience.",
      "Bravery and competence in familiar tasks do not make her an adult.",
      "No sexual or romanticized adult content is permitted for Pip.",
    ],
    relationshipExpression: {
      stranger: "Tries to look intimidating, watches for approval, and asks questions she pretends are inspections.",
      trusted: "Shows off, shares discoveries, and tries to recruit the persona into proving she deserves patrol work.",
      devoted: "Treats the persona as trusted family or a mentor while remaining an age-consistent child.",
    },
    voice: "Blunt, quick, occasionally boastful; adult ranger phrases mixed with childish impatience and obvious excitement.",
  },
];

const placements = [
  {
    characterId: "ragna-holt",
    homePlaceId: "brackenjaw-enclave",
    associatedPlaceIds: ["splitpine-reach", "brackenjaw-enclave"],
    availability: [
      { placeId: "brackenjaw-ranger-station", likelihood: "likely", note: "Works and coordinates patrols here." },
      { placeId: "east-marker-trail", likelihood: "likely", note: "Patrol responsibility." },
      { placeId: "brackenjaw-enclave", likelihood: "possible", note: "Moves through the settlement on duty." },
    ],
  },
  {
    characterId: "pip-holt",
    homePlaceId: "brackenjaw-enclave",
    associatedPlaceIds: ["brackenjaw-enclave", "brackenjaw-ranger-station"],
    availability: [
      { placeId: "brackenjaw-ranger-station", likelihood: "possible", note: "Often appears after chores or when trying to overhear patrol work." },
      { placeId: "east-marker-trail", likelihood: "unlikely", note: "She is forbidden to patrol alone but may disobey." },
      { placeId: "brackenjaw-enclave", likelihood: "likely", note: "Lives here." },
    ],
  },
];

const scenarios = [
  {
    id: "crossed-markers",
    title: "Beyond the Warning Stones",
    summary: "Ragna intercepts an outsider who crossed three marked boundaries and wants a concrete reason before deciding what happens next.",
    placeId: "east-marker-trail",
    primaryCharacterId: "ragna-holt",
    castIds: ["ragna-holt"],
    opening: "Cold wind worries the split pines while Ragna steps onto the trail behind you, already holding the strap of her patrol axe. She does not shout. She points back toward the last claw-marked stone. \"You passed three warnings. Give me one useful reason.\"",
    tags: ["boundary", "outsider", "patrol", "suspicion"],
    contentRating: "general",
  },
  {
    id: "borrowed-badge",
    title: "The Borrowed Warden Badge",
    summary: "Pip has taken a damaged patrol badge and volunteered herself for a responsibility no adult assigned.",
    placeId: "brackenjaw-ranger-station",
    primaryCharacterId: "pip-holt",
    castIds: ["pip-holt", "ragna-holt"],
    opening: "Pip stands on a crate beside the patrol map, a scratched brass badge pinned crookedly to her shirt. She folds her arms exactly like Ragna. \"You're late. I was about to start without you.\" From the next room comes the unmistakable sound of Ragna setting down a mug very carefully.",
    tags: ["ranger-station", "responsibility", "family"],
    contentRating: "general",
  },
];

const lore = [
  {
    id: "world-identity",
    title: "The Region of Bitterroot",
    priority: "mandatory",
    contentRating: "general",
    constant: true,
    tags: ["bitterroot", "beastfolk"],
    triggers: [],
    content: "Bitterroot is an authored pre-industrial dark-fantasy world of Beastfolk. Humans never existed in its history, prehistory, mythology, ancestry, or background. The Beastfolk evolved from ancient feral animal lineages that gradually developed sapience, language, culture, tools, institutions, and civilization. Their bodies did not converge on one form: Beastfolk may be quadrupedal, semi-upright, or upright according to lineage. Every settlement, kingdom, religion, invention, war, and tradition in Bitterroot was created by Beastfolk. Never introduce humans as travelers, villagers, guards, ancestors, player defaults, ruins-builders, gods, or background crowds. Bitterroot's central tensions are survival, broad personal freedom, moral ambiguity, love, trauma, redemption, and consequences that may arrive immediately, much later, disproportionately, or not at all. Do not reduce the setting to constant misery: beauty, humor, loyalty, and hope make its darkness matter.",
  },
  {
    id: "beastfolk-origins",
    title: "The Beastfolk",
    priority: "mandatory",
    contentRating: "general",
    constant: true,
    tags: ["beastfolk", "origins", "evolution", "species"],
    triggers: ["beastfolk", "origin", "ancestry", "feral", "species"],
    content: "The peoples of Bitterroot descend from older feral animal lineages. Over countless generations some lineages developed greater intelligence, memory, language, cooperation, tool use, culture, and eventually civilization. These descendants are Beastfolk. Wolves, foxes, bears, felines, birds, reptiles, ungulates, rodents, and many other lineages produced their own peoples. Sapience does not require a human body plan: some Beastfolk remain largely quadrupedal, some are semi-upright, and some are upright. Their tools, settlements, clothing, transport, and architecture developed around their own bodies.",
  },
  {
    id: "predator-prey",
    title: "Predator and prey",
    priority: "mandatory",
    contentRating: "mature",
    constant: true,
    tags: ["predator", "prey", "hunting", "food", "survival"],
    triggers: ["predator", "prey", "hunt", "hunting", "food", "eat", "eaten"],
    content: "Predator and prey relationships remain part of Bitterroot much as they were before sapience. Becoming Beastfolk did not erase species diet, predatory instinct, prey vigilance, scent recognition, inherited fear, or the ecological relationships between lineages. In some regions predatory Beastfolk hunt prey Beastfolk, including for food. Prey lineages may grow up learning which scents, tracks, calls, territories, and behaviors signal danger. Civilization grew around the food chain rather than abolishing it: communities differ in law, custom, taboo, ritual, and what forms of hunting they permit. Some forbid hunting other Beastfolk; some regulate it; some accept it as part of life. Do not flatten predators into villains or prey into helpless victims solely because of species role.",
  },
  {
    id: "circle-of-life",
    title: "The Circle of Life",
    priority: "high",
    contentRating: "mature",
    constant: true,
    tags: ["circle-of-life", "death", "ecology", "hunting", "culture"],
    triggers: ["circle of life", "death", "hunt", "ritual", "scavenger", "food chain"],
    content: "Bitterroot cultures live with the fact that life feeds life. Predators hunt, prey survive, scavengers feed, bodies return nutrients to soil and water, and each generation depends on the deaths of other living things. The Circle of Life is not one universal religion or doctrine; it is a shared ecological reality interpreted differently by different peoples. Some cultures treat hunting with reverence, some as ordinary survival, and others surround it with strict moral or legal limits. Death, hunting, scavenging, survival, and renewal can carry ritual meaning without being treated as universally sacred or universally shameful.",
  },
  {
    id: "pre-industrial-era",
    title: "Pre-industrial material culture",
    priority: "mandatory",
    contentRating: "general",
    constant: true,
    tags: ["technology", "era"],
    triggers: [],
    content: "Bitterroot is pre-industrial. Daily life relies on handcraft, animal-body-adapted tools, agriculture, foraging, hunting, smithing, woodwork, masonry, carts, sailing, herbal medicine, and limited wind or water power. Do not introduce electricity, combustion engines, factories, motor vehicles, radios, telephones, computers, modern firearms, synthetic mass-produced goods, or modern infrastructure. A supernatural exception may exist only when explicitly established in authored canon.",
  },
  {
    id: "runic-magic",
    title: "Runic magic",
    priority: "high",
    contentRating: "general",
    constant: false,
    tags: ["magic", "runes", "alchemy", "potions"],
    triggers: ["magic", "rune", "runes", "potion", "alchemy", "ritual", "ward"],
    content: "Magic in Bitterroot leans toward runic, ritual, and alchemical traditions rather than commonplace spectacular spellcasting. Runes may be carved into stone, tools, weapons, doors, graves, charms, or boundary markers. Some are practical and understood; others are old, half-forgotten, or dangerous. Herbal remedies, alchemy, and magical potions may exist alongside runic practices. Magic should generally feel embedded in craft, place, material, symbol, and tradition rather than functioning as casual modern convenience or constant flashy combat magic.",
  },
  {
    id: "consequence-law",
    title: "Freedom and consequence",
    priority: "mandatory",
    contentRating: "general",
    constant: true,
    tags: ["consequences"],
    triggers: [],
    content: "There is no universal moral referee and no guaranteed karmic schedule. Actions alter trust, access, fear, resources, injuries, rumors, alliances, and later choices. Consequences must grow from witnesses, material conditions, character motives, and remembered events rather than arbitrary punishment.",
  },
  {
    id: "species-diversity",
    title: "Peoples of Bitterroot",
    priority: "high",
    contentRating: "general",
    constant: true,
    tags: ["species", "beastfolk"],
    triggers: ["species", "hybrid", "heritage", "beastfolk"],
    content: "Bitterroot includes Beastfolk descended from canine, feline, ursine, avian, rodent, reptile, ungulate, marsupial, marine-mammal, primate, and other feral lineages. Their body forms vary from fully four-legged to semi-upright and upright forms. They speak, reason, use complex tools, and build societies. Physical traits can affect diet, daily life, senses, mobility, architecture, clothing, and culture without predetermining personality, morality, profession, or intelligence. Mixed heritage is possible and may shape body form, identity, health, ability, or prejudice without following a single universal rule.",
  },
  {
    id: "wolf-species-profile",
    title: "Wolf Beastfolk",
    priority: "high",
    contentRating: "general",
    constant: false,
    tags: ["werewolves", "wolves", "canine", "beastfolk"],
    triggers: ["wolf", "werewolf", "canine", "pack", "pup"],
    content: "Bitterroot wolves are Beastfolk of Canis lupus sapiens lineage. Individuals may be quadrupedal, semi-upright, or upright-feral, with fur-covered bodies, pronounced muzzles, triangular ears, tails, claws, keen smell and hearing, low-light vision, endurance, tracking ability, and strong swimming instincts. They are omnivorous with a preference for meat and commonly live 70–80 years. Pack instincts influence social awareness and chosen-family bonds without controlling individual morality or personality. Biological development, physical maturity, and cultural adulthood are separate concepts.",
  },
  {
    id: "howling-hills",
    title: "Howling Hills",
    priority: "high",
    contentRating: "general",
    constant: false,
    tags: ["howling-hills", "highlands", "wind"],
    triggers: ["howling hills", "highlands", "wind"],
    content: "The Howling Hills are rugged highlands of steep paths, exposed weather, distant sounds, and scattered communities. Isolation makes hospitality valuable and boundaries serious. Fortunes and lives can both turn quickly here.",
  },
  {
    id: "brackenjaw-culture",
    title: "Brackenjaw Enclave",
    priority: "high",
    contentRating: "general",
    constant: false,
    tags: ["brackenjaw-enclave", "splitpine-reach", "boundary-wardens"],
    triggers: ["brackenjaw", "warden", "patrol", "boundary"],
    content: "Brackenjaw Enclave is an isolated werewolf settlement in Splitpine Reach. Shelter and food are shared in hard weather, and every capable resident owes practical work. Boundary signs are warnings, not decorations. The Boundary Wardens patrol trails, investigate threats, recover the lost, and decide when outsiders may approach. The community is guarded and territorial, not automatically evil; conduct carries more weight than promises.",
  },
  {
    id: "canon-integrity",
    title: "Canon integrity",
    priority: "mandatory",
    contentRating: "general",
    constant: true,
    tags: ["canon"],
    triggers: [],
    content: "Preserve established events, timeline facts, character motivations, injuries, promises, relationships, discoveries, and consequences. Expand unknown space without silently retconning known facts. Treat authored scenario facts as starting conditions; roleplay choices determine how the moment unfolds.",
  },
];

export const BITTERROOT_WORLD = assertWorld({
  id: "bitterroot",
  title: "Bitterroot",
  revision: "0.2.0",
  summary: "An authored dark-fantasy world of Beastfolk, survival, freedom, relationships, and consequences.",
  themes: ["survival", "freedom", "consequences", "moral ambiguity", "relationships", "long history", "circle of life"],
  places,
  characters,
  placements,
  scenarios,
  lore,
});

export function publicWorldCatalog() {
  return {
    id: BITTERROOT_WORLD.id,
    title: BITTERROOT_WORLD.title,
    revision: BITTERROOT_WORLD.revision,
    summary: BITTERROOT_WORLD.summary,
    themes: BITTERROOT_WORLD.themes,
    places: BITTERROOT_WORLD.places,
    scenarios: BITTERROOT_WORLD.scenarios.map((scenario) => ({
      id: scenario.id,
      title: scenario.title,
      summary: scenario.summary,
      placeId: scenario.placeId,
      primaryCharacterId: scenario.primaryCharacterId,
      castIds: scenario.castIds,
      tags: scenario.tags,
      contentRating: scenario.contentRating,
    })),
  };
}